### ISSUE TITLE
Polling Features

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/dot-one#7]
**Poll Options:**
1) Multiple Choice 
Who do you support for President of the USA? 
a) Biden 
b) Trump 
c) Kennedy Jr.
d) none of the above

2) Yes or No 
Do you believe that healthcare should be free for all?  Yes or No?

3) Ranking 1-5 
Rank these candidates in order of preference O Biden O Trump O Kennedy Jr. 

* User Generated
* AI bot that combines polls that are the same
* Sorted by region
* Trending polls bumped

**Comment by timofeysie** [comment]
Do polling features stay open forever?  Can someone come back a month later and still answer the poll?
For example, twitter has a time limit and also shows results:


![Image](https://github.com/timofeysie/dot-one/assets/2747740/d6f54c57-3a0f-4598-9090-8889f325c537)

When will the results of our polls be shown?  Will it show answers before the end of a possible time limit?

If it's up to me, I would an AMP quiz which would be on the AMP version of .one (ie, the one that loads in 2 seconds rather than the one that loads in 20 seconds and can be used for content creation).  You can see a demo of an AMP quiz here: https://amp.dev/documentation/examples/components/amp-story-interactive-quiz/preview/

**Comment by MikeInKorea** [comment]
interseting... I think they stay open forever.... but are measured and presented with a time component. (eg. over the last 6 months, 81% of citizens polled agree that...) . That actually provides an great way to measure shifts in public opinion as well.

**Comment by MikeInKorea** [comment]
You can't vote again, but it would be great if you could change your vote

**Comment by MikeInKorea** [comment]
Show results after voting

**Comment by timofeysie** [comment]
The polls feature has been deployed:
![image](https://github.com/user-attachments/assets/c9468561-04da-4da7-a573-a43631064aab)

However, I have having issue logging in due to network issues which I will have to resolve later.

**Comment by timofeysie** [comment]
Here are some screenshots for now:
![image](https://github.com/user-attachments/assets/3f331472-b1f8-4c33-a1ce-f0cf3ad53117)

The site in general needs a style overhaul which I will open another task for.
